language: java

addons:
  srcclr: true

cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/.sonar/cache

jdk:
  - oraclejdk8

#script: mvn clean install sonar:sonar -Dsonar.host.url=http://192.210.193.136:9000/ -Dsonar.login=$SONAR_TOKEN
